swagger: "2.0"

info:
  title: "Example Server API"
  description: "This is document for Example Server API"
  version: "1.0.0"

host: "api.example.com"
basePath: "/api/v1"

schemes:
- https

tags:
  - name: "Pet"
    description: "API for Pet"
  - name: "Order"
    description: "API for Order"
  - name: "Category"
    description: "API for Category"
  - name: "Tag"
    description: "API for Tag"
  - name: "Store"
    description: "API for Store"
  - name: "User"
    description: "API for User"

definitions:
  Pet:
    $ref: "/api_docs/v1/definitions/pet.yaml"
  Order:
    $ref: "/api_docs/v1/definitions/order.yaml"
  Category:
    $ref: "/api_docs/v1/definitions/category.yaml"
  User:
    $ref: "/api_docs/v1/definitions/user.yaml"
  Tag:
    $ref: "/api_docs/v1/definitions/tag.yaml"
  ApiResponse:
    $ref: "/api_docs/v1/definitions/api_response.yaml"

paths:
  /pet:
    $ref: "/api_docs/v1/paths/pets/pet.yaml"
  /pet/findByStatus:
    $ref: "/api_docs/v1/paths/pets/pet_findByStatus.yaml"
  /pet/{petId}:
    $ref: "/api_docs/v1/paths/pets/pet_{petId}.yaml"
